import xwaf.utils.configs as config_utils


def options(ctx):
    ctx.add_option('--config', action='store', default='')


def configure(conf):
    def make_config(name, flags):
        conf.setenv(name)
        conf.load('xwaf.compiler_xcc')
        conf.env.XCC_FLAGS = flags

    for key, value in CONFIGS.iteritems():
        make_config(key, value)


def build(bld):
    if not config_utils.check_build_config(bld, CONFIGS):
        return

    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_gpio', 'lib_logging']

    bld.env.TARGET_ARCH = 'SLICEKIT-L16'

    prog = bld.program(depends_on=depends_on)


CONFIGS = {
    'input_timestamps': [
        '-O2', '-g', '-save-temps', '-DDEBUG_PRINT_ENABLE=1', '-report',
        '-DEVENTS=0', '-DTIMESTAMPS=1'
    ],
    'input_events': [
        '-O2', '-g', '-save-temps', '-DDEBUG_PRINT_ENABLE=1', '-report',
        '-DEVENTS=1', '-DTIMESTAMPS=0'
    ],
    'input_basic': [
        '-O2', '-g', '-save-temps', '-DDEBUG_PRINT_ENABLE=1', '-report',
        '-DEVENTS=0', '-DTIMESTAMPS=0'
    ],
}

config_utils.register_configs(CONFIGS)
